config/routes.rb
EuroExim::Application.routes.draw do

  resources :agencies

  match '/bo_reports/manage' => 'bo_reports#manage'
  match '/find_booking' => "booking_orders#find_booking"
  resources :bo_reports

  resources :booking_reports

  resources :booking_emailers

  resources :sales_call_enquiries

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :sales_call_entries

  resources :customers

  resources :bookings do as_routes end
  resources :cities do as_routes end
  resources :bookings

  resources :booking_orders

  resources :emailers

    devise_scope :user do
      post '/users' => 'users/registrations#create'
    end

   devise_for :users do
  ActiveAdmin.routes(self)
     get "users/sign_in", :to => "devise/sessions#new"
     get "users/sign_out", :to => "devise/sessions#destroy"
  end
  match '/reports/fields'
  root :to => 'home#index'
  resources :reports
  match '/add_booking' => 'booking_orders#booking'
  match '/send_email_to_customer' => 'booking_orders#send_email_to_customer'
  match '/send_email_to_user' => 'booking_orders#send_email_to_user'
  mount Ckeditor::Engine => '/ckeditor'

  match '(/:action(/:id(.:format)))' => 'home#:action'
end

app/models/booking_report.rb
class BookingReport < ActiveRecord::Base #This model is unused
  attr_accessible :description, :name
end

app/controllers/booking_reports_controller.rb
class BookingReportsController < InheritedResources::Base
end

app/helpers/booking_reports_helper.rb
module BookingReportsHelper
end

app/views/booking_reports/_form.html.erb
<%= form_for(@booking_report) do |f| %>
  <% if @booking_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking_report.errors.count, "error") %> prohibited this booking_report from being saved:</h2>

      <ul>
      <% @booking_report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit :create, :class => "btn btn-info" %>
  </div>
<% end %>

app/views/booking_reports/edit.html.erb
<h1>Editing booking_report</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking_report %> |
<%= link_to 'Back', booking_reports_path %>

app/views/booking_reports/index.html.erb
<h1>Listing booking_reports</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @booking_reports.each do |booking_report| %>
  <tr>
    <td><%= booking_report.name %></td>
    <td><%= booking_report.description %></td>
    <td><%= link_to 'Show', booking_report %></td>
    <td><%= link_to 'Edit', edit_booking_report_path(booking_report) %></td>
    <td><%= link_to 'Destroy', booking_report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Booking report', new_booking_report_path %>

app/views/booking_reports/new.html.erb
<h1>New booking_report</h1>

<%= render 'form' %>

<%= link_to 'Back', booking_reports_path %>

app/views/booking_reports/show.html.erb
<div class="row">
        <div class="col-md-12">
          <!-- BEGIN PAGE TITLE & BREADCRUMB-->
          <h3 class="page-title">
          Dashboard <small>statistics and more</small>
          </h3>
          <ul class="page-breadcrumb breadcrumb">
            <li>
              <i class="fa fa-home"></i>
              <a href="index.html">Home</a>
              <i class="fa fa-angle-right"></i>
            </li>
            <li>
              <a href="#">Dashboard</a>
            </li>
            <li class="pull-right">
              <div data-original-title="Change dashboard date range" data-placement="top" class="dashboard-date-range tooltips" id="dashboard-report-range" style="display: block;">
                <i class="fa fa-calendar"></i>
                <span>March 19, 2014 - April 17, 2014</span>
                <i class="fa fa-angle-down"></i>
              </div>
            </li>
          </ul>
          <!-- END PAGE TITLE & BREADCRUMB-->
        </div>
      </div>