config/routes.rb
EuroExim::Application.routes.draw do

  resources :agencies

  match '/bo_reports/manage' => 'bo_reports#manage'
  match '/find_booking' => "booking_orders#find_booking"
  resources :bo_reports

  resources :booking_reports

  resources :booking_emailers

  resources :sales_call_enquiries

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :sales_call_entries

  resources :customers

  resources :bookings do as_routes end
  resources :cities do as_routes end
  resources :bookings

  resources :booking_orders

  resources :emailers

    devise_scope :user do
      post '/users' => 'users/registrations#create'
    end

   devise_for :users do
  ActiveAdmin.routes(self)
     get "users/sign_in", :to => "devise/sessions#new"
     get "users/sign_out", :to => "devise/sessions#destroy"
  end
  match '/reports/fields'
  root :to => 'home#index'
  resources :reports
  match '/add_booking' => 'booking_orders#booking'
  match '/send_email_to_customer' => 'booking_orders#send_email_to_customer'
  match '/send_email_to_user' => 'booking_orders#send_email_to_user'
  mount Ckeditor::Engine => '/ckeditor'

  match '(/:action(/:id(.:format)))' => 'home#:action'
end

app/models/agency.rb
class Agency < ActiveRecord::Base
  attr_accessible :email, :name,:country,:city,:sector,:network,:pics,:phone_nos,:website,:coordinator,:coordinator_email,:notes,:approved
  validates :name, :presence => true
  validates :email, :presence => true
end

app/controllers/agencies_controller.rb
class AgenciesController < InheritedResources::Base
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/views/agencies/_form.html.erb
<%= form_for(@agency) do |f| %>
  <% if @agency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agency.errors.count, "error") %> prohibited this agency from being saved:</h2>

      <ul>
      <% @agency.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :sector %><br />
    <%= f.text_field :sector %>
  </div>
  <div class="field">
    <%= f.label :network %><br />
    <%= f.text_field :network %>
  </div>
  <div class="field">
    <%= f.label :pics %><br />
    <%= f.text_field :pics %>
  </div>
  <div class="field">
    <%= f.label :phone_nos %><br />
    <%= f.text_field :phone_nos %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :coordinator %><br />
    <%= f.text_field :coordinator %>
  </div>
  <div class="field">
    <%= f.label :coordinator_email %><br />
    <%= f.text_field :coordinator_email %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </div>
  <% if current_user.admin? %>
    <div class="field">
      <%= f.label :approved %><br />
      <%= f.check_box :approved %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/agencies/edit.html.erb
<h1>Editing agency</h1>

<%= render 'form' %>

<%= link_to 'Show', @agency %> |
<%= link_to 'Back', agencies_path %>

app/views/agencies/index.html.erb
<h1>Listing agencies</h1>

<table class="table">
  <tr>
    <th>Email</th>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>

<% @agencies.each do |agency| %>
  <tr>
    <td><%= agency.email %></td>
    <td><%= agency.name %></td>
    <td><%= agency.country %></td>
    <td><%= agency.city %></td>
    <td><%= agency.approved %></td>
    <td><%= link_to 'Show', agency %></td>
    <% if current_user.admin? %>
      <td><%= link_to 'Edit', edit_agency_path(agency) %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Agency', new_agency_path %>

app/views/agencies/new.html.erb
<h1>New agency</h1>

<%= render 'form' %>

<%= link_to 'Back', agencies_path %>

app/views/agencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @agency.email %>
</p>

<p>
  <b>Name:</b>
  <%= @agency.name %>
</p>

<p><b>country:</b>
<%= @agency.country %>
</p>
<p>
<b>city:</b>
<%= @agency.city %>
</p>
<p>
<b>sector:</b>
<%= @agency.sector %>
</p>
<p>
<b>network:</b>
<%= @agency.network %>
</p>
<p>
<b>pics:</b>
<%= @agency.pics %>
</p>
<p>
<b>phone_nos:</b>
<%= @agency.phone_nos %>
</p>
<p>
<b>website:</b>
<%= @agency.website %>
</p>
<p>
<b>coordinator:</b>
<%= @agency.coordinator %>
</p>
<p>
<b>coordinator_email:</b>
<%= @agency.coordinator_email %>
</p>
<p>
<b>notes:</b>
<%= @agency.notes %>
</p>
<p>
<b>approved:</b>
<%= @agency.approved %>
</p>

<% if current_user.admin? %>
<%= link_to 'Edit', edit_agency_path(@agency) %> 
|
<% end %>

<%= link_to 'Back', agencies_path %>