config/routes.rb
EuroExim::Application.routes.draw do

  resources :agencies

  match '/bo_reports/manage' => 'bo_reports#manage'
  match '/find_booking' => "booking_orders#find_booking"
  resources :bo_reports

  resources :booking_reports

  resources :booking_emailers

  resources :sales_call_enquiries

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :sales_call_entries

  resources :customers

  resources :bookings do as_routes end
  resources :cities do as_routes end
  resources :bookings

  resources :booking_orders

  resources :emailers

    devise_scope :user do
      post '/users' => 'users/registrations#create'
    end

   devise_for :users do
  ActiveAdmin.routes(self)
     get "users/sign_in", :to => "devise/sessions#new"
     get "users/sign_out", :to => "devise/sessions#destroy"
  end
  match '/reports/fields'
  root :to => 'home#index'
  resources :reports
  match '/add_booking' => 'booking_orders#booking'
  match '/send_email_to_customer' => 'booking_orders#send_email_to_customer'
  match '/send_email_to_user' => 'booking_orders#send_email_to_user'
  mount Ckeditor::Engine => '/ckeditor'

  match '(/:action(/:id(.:format)))' => 'home#:action'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # attr_accessible :address_1, :address_2, :city, :contact_person, :email, :name, :phone, :zip_code
  validates :email, :presence => true
  validates :name, :presence => true
  validates :email, :uniqueness => true, :on => :create
  validates :name, :uniqueness => true, :on => :create
  
	require 'csv'
	UPLOAD_TYPES = [
		SELECT = "Select",
		EXPORTER = "Exporter",
		EXPORTER_REPORT = "Exporter Report"
	]

	validates :name, :presence => true
	def self.upload_customer(file,nomination)
		column_names = Customer.column_names
		csv_text = File.read(file)
		csv = CSV.parse(csv_text, :headers => true)
		total = csv.count
		saved = 0
		csv.each do |row|
		  row = row.to_hash.with_indifferent_access
	    hash = {}
	    row.to_hash.each_pair do |k,v|
	      hash[k.downcase] = v 
	    end
	    new_hash = {}
		  column_names.each do |cn|
		  	new_hash[cn] = hash[cn]
		  end
		  shipper = Customer.new(new_hash.symbolize_keys)
		  shipper.nomination = nomination
		  shippers = Customer.find(:all, :conditions => ["UPPER(name) like ?", "%#{shipper.name}%"])
		  if shippers.empty?
		  	if shipper.save
		  		saved += 1
		  	end
		  else
		  	saved += 1
		  end

		end
		return total , saved
	end
end

app/controllers/customers_controller.rb
class CustomersController < InheritedResources::Base
	before_filter :authenticate_user!
	def index
		if current_user.nomination?
			@tasks_grid = initialize_grid(Customer.where(nomination: true))
		else
			@tasks_grid = initialize_grid(Customer.where(nomination: false))
		end
	end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :address1 %>
    <%= f.text_field :address_1 %>
  </div>

  <div class="field">
    <%= f.label :address2 %>
    <%= f.text_field :address_2 %>
  </div>

  <div class="field">
    <%= f.label :pic %>
    <%= f.text_field :contact_person %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :mobile %>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :sales_person %>
    <%= f.text_field :sales_person %>
  </div>
  <div class="actions">
    <% if current_user.sales? %>
      <%= f.hidden_field :approved, :value => false %>
    <% end %>
    <% if current_user.nomination? %>
      <%= f.hidden_field :nomination, :value => true %>
    <% else %>
      <%= f.hidden_field :nomination, :value => false %>
    <% end %> 
    <%= f.submit "save", :class => 'btn btn-info'%>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>
    
<%= link_to 'New Customer', new_customer_path, :class => 'btn btn-medium btn-info', :style =>'color:white'  %>
<br>
<br>

<%= define_grid(@tasks_grid, hide_submit_button: true, hide_reset_button: true) do |g|
  g.column name:  'Name', attribute: 'name', detach_with_id: :name_filter
  g.column name:  'City', attribute: 'city', detach_with_id: :city_filter
  g.column name:  'Address1', attribute: 'address_1', detach_with_id: :address_1_filter
  g.column name:  'Address2', attribute: 'address_2', detach_with_id: :address_2_filter
  g.column name:  'PIC', attribute: 'contact_person', detach_with_id: :contact_person_filter
  g.column name:  'Sales Person', attribute: 'sales_person', detach_with_id: :sales_person_filter
  g.column name:  'Email', attribute: 'email', detach_with_id: :email_filter
  g.column  :in_csv => false do |task|
    link_to('Edit', edit_customer_path(task))
  end
end
%>

<div class="row-fluid">
  <div class="span1">
    Name:
  </div>
  <div class="span3">
    <%= grid_filter @tasks_grid, :name_filter %>
  </div>
  <div class="span1">
    City:
  </div>
  <div class="span3">
    <%= grid_filter @tasks_grid, :city_filter %>
  </div>
  <div class="span1">
    Sales Person:
  </div>
  <div class="span3">
    <%= grid_filter @tasks_grid, :sales_person_filter %>
  </div>
  <div class="span1">
    Email:
  </div>
  <div class="span3">
    <%= grid_filter @tasks_grid, :email_filter %>
  </div>
   <div class="span1">
    Pic:
  </div>
  <div class="span3">
    <%= grid_filter @tasks_grid, :contact_person_filter %>
  </div>
  
</div>
<div class="row-fluid">
  <div class="span12">
    <div class="external-buttons">
  <button class="wg-external-submit-button" data-grid-name="grid">Submit</button>
  <button class="wg-external-reset-button" data-grid-name="grid">Reset</button>
    </div>
    </div>
</div>
    
<div class="row-fluid">
  <div class="span12">
    <%= render_grid(@tasks_grid)  %>
    </div>
    </div>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @customer.name %>
</p>

<p>
  <b>Address 1:</b>
  <%= @customer.address_1 %>
</p>

<p>
  <b>Address 2:</b>
  <%= @customer.address_2 %>
</p>

<p>
  <b>City:</b>
  <%= @customer.city %>
</p>

<p>
  <b>Zip code:</b>
  <%= @customer.zip_code %>
</p>

<p>
  <b>Contact person:</b>
  <%= @customer.contact_person %>
</p>

<p>
  <b>Email:</b>
  <%= @customer.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @customer.phone %>
</p>



<%= link_to 'Back', customers_path %>