config/routes.rb
EuroExim::Application.routes.draw do

  resources :agencies

  match '/bo_reports/manage' => 'bo_reports#manage'
  match '/find_booking' => "booking_orders#find_booking"
  resources :bo_reports

  resources :booking_reports

  resources :booking_emailers

  resources :sales_call_enquiries

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :sales_call_entries

  resources :customers

  resources :bookings do as_routes end
  resources :cities do as_routes end
  resources :bookings

  resources :booking_orders

  resources :emailers

    devise_scope :user do
      post '/users' => 'users/registrations#create'
    end

   devise_for :users do
  ActiveAdmin.routes(self)
     get "users/sign_in", :to => "devise/sessions#new"
     get "users/sign_out", :to => "devise/sessions#destroy"
  end
  match '/reports/fields'
  root :to => 'home#index'
  resources :reports
  match '/add_booking' => 'booking_orders#booking'
  match '/send_email_to_customer' => 'booking_orders#send_email_to_customer'
  match '/send_email_to_user' => 'booking_orders#send_email_to_user'
  mount Ckeditor::Engine => '/ckeditor'

  match '(/:action(/:id(.:format)))' => 'home#:action'
end

app/views/layouts/application.html.erb
	<!DOCTYPE html>
<html>
<head>
  <title>Euro Square</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "http://code.jquery.com/jquery-1.8.1.js" %>
  <script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
  <%= csrf_meta_tags %>
  <style>
	.pollo select{
		width:100px !important;
	}
</style>
</head>
<body>
<body class="fixed-top">
	<!-- BEGIN HEADER -->
	<div id="header" class="navbar navbar-inverse navbar-fixed-top">
		<!-- BEGIN TOP NAVIGATION BAR -->
		<div class="navbar-inner">
			<div class="container-fluid">
				<!-- BEGIN LOGO -->
				<a class="brand" href="/index">
				<img src="/assets/logo.png" alt="WebAsianSystems" />
				</a>
				<!-- END LOGO -->
				<!-- BEGIN RESPONSIVE MENU TOGGLER -->
				<a class="btn btn-navbar collapsed" id="main_menu_trigger" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="arrow"></span>
				</a>
				<!-- END RESPONSIVE MENU TOGGLER -->
				<div class="top-nav">
					<div class="nav pull-right">
						<span class="user-and-role"><%=current_user.name%> (<%=current_user.user_role%>)</span>
						<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
					</div>
					<!-- END TOP NAVIGATION MENU -->
				</div>
			</div>
		</div>
		<!-- END TOP NAVIGATION BAR -->
	</div>
	<!-- END HEADER -->
	<!-- BEGIN CONTAINER -->
	<div id="container" class="row-fluid">
		<!-- BEGIN SIDEBAR -->
		<div id="sidebar" class="nav-collapse collapse">
			<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
			<div class="sidebar-toggler hidden-phone"></div>
			<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
			<!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
			<div class="navbar-inverse">
				<form class="navbar-search visible-phone">
					<input type="text" class="search-query" placeholder="Search" />
				</form>
			</div>
			<!-- END RESPONSIVE QUICK SEARCH FORM -->
			<!-- BEGIN SIDEBAR MENU -->
			<ul>
				<li class="<%= active_class('/index') %>">
					<%= link_to '/index' do -%>
						<i class="icon-home"></i>
						<span class="title">Dashboard</span>
					<% end -%>
				</li>
				<% if current_user.operation? %>
					<li class="<%= active_class(customers_path) %>">
						<%= link_to customers_path do -%>
							<i class="icon-spinner"></i>
							<span class="title">Customer Details</span>
						<% end -%>
					</li>
				<% end %>
				<% if current_user.admin? || current_user.nomination? %>
					<li class="<%= active_class('upload_epxorters') %>">
						<%= link_to '/upload_epxorters' do -%>
							<i class="icon-user"></i>
							<span class="title">Upload Customer</span>
						<% end -%>
					</li>
					<li class="<%= active_class(customers_path) %>">
						<%= link_to customers_path do -%>
							<i class="icon-spinner"></i>
							<span class="title">Customer Details</span>
						<% end -%>
					</li>
				<% end %>
				<%# All users get to see the Bookings link %>
				<li class="<%= active_class('/booking_orders') %>">
					<%= link_to '/booking_orders' do -%>
						<i class="icon-file"></i>
						<span class="title">Bookings</span>
					<% end -%>
				</li>
				<% if current_user.admin? || current_user.nomination? %>
					<li class="<%= active_class('/agencies') %>">
						<%= link_to '/agencies' do -%>
							<i class="icon-file"></i>
							<span class="title">Agency</span>
						<% end -%>
					</li>
				<% end %>
				<% if current_user.admin? || current_user.sales? %>
					<li class="<%= active_class(sales_call_entries_path) %>">
						<%= link_to sales_call_entries_path do -%>
							<i class="icon-th-list"></i>
							<span class="title">Sales Call Entries</span>
						<% end -%>
					</li>
					<li class="<%= active_class(sales_call_enquiries_path) %>">
						<%= link_to sales_call_enquiries_path do -%>
							<i class="icon-leaf"></i>
							<span class="title">Enquiry</span>
						<% end -%>
					</li>
				<% end %>
				<% if current_user.sales? %>
					<li class="<%= active_class(new_customer_path) %>">
						<%= link_to new_customer_path do -%>
							<i class="icon-user"></i>
							<span class="title">New Customer</span>
						<% end -%>
					</li>
				<% end %>
<!-- 				<li class="<%= active_class('exporter_export_details') %>">
					<%= link_to '/exporter_export_details' do -%>
						<i class="icon-th-list"></i>
						<span class="title">Exporter Export Details</span>
					<% end -%>
				</li>					 -->
				<% if current_user.admin? %>
					<li class="<%= active_class(emailers_path) %>">
						<%= link_to emailers_path do -%>
							<i class="icon-comment"></i>
							<span class="title">Emailer</span>
						<% end -%>
					</li>
				<% end %>

				<li class="<%= active_class(bo_reports_path) %>">
					<%= link_to bo_reports_path do -%>
						<i class="icon-bar-chart"></i>
						<span class="title">Reports</span>
					<% end -%>
				</li>
				<% if current_user.admin? %>
					<li class="<%= active_class('/bo_reports/manage') %>">
						<%= link_to "/bo_reports/manage" do -%>
							<i class="icon-bar-chart"></i>
							<span class="title">Manage Reports</span>
						<% end -%>
					</li>
				<% end %>
			</ul>
			<!-- END SIDEBAR MENU -->
		</div>
		<!-- END SIDEBAR -->
		<!-- BEGIN PAGE -->
		<div id="body" >
			<div class="container-fluid">
				<div class="row-fluid">
					<div class="span12">
						<div id="page" class="dashboard">
							<%= yield %>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- END PAGE -->
	</div>
	<!-- END CONTAINER -->
	<!-- BEGIN FOOTER -->
	<div id="footer">
		2013 &copy; Euro Exim.
		<div class="span pull-right">
			<span class="go-top"><i class="icon-arrow-up"></i></span>
		</div>
	</div>
  <link rel="stylesheet" href="/chosen.css">
  <script src="/chosen.jquery.js" type="text/javascript"></script>
  <script type="text/javascript">
    var config = {
      '.chosen-select'           : {},
      '.chosen-select-deselect'  : {allow_single_deselect:true},
      '.chosen-select-no-single' : {disable_search_threshold:10},
      '.chosen-select-no-results': {no_results_text:'Oops, nothing found!'},
      '.chosen-select-width'     : {width:"95%"}
    }
    for (var selector in config) {
      $(selector).chosen(config[selector]);
    }
    jQuery(document).ready(function($) {
		  $( ".datepicker" ).each(function(){
		  	$(this).datepicker({
		  		"dateFormat": 'yy-mm-dd'
		  	});
		  });
		});
  </script>
</body>
</html>

app/views/layouts/application1.html.erb
  <!DOCTYPE html>
<html>
<head>
  <title>Euro Square</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application1" %>

  <%= csrf_meta_tags %>
  <style>
  .pollo select{
    width:100px !important;
  }
</style>
</head>
<body>
<body class="fixed-top">
  <!-- BEGIN HEADER -->
  <div id="header" class="navbar navbar-inverse navbar-fixed-top">
    <!-- BEGIN TOP NAVIGATION BAR -->
    <div class="navbar-inner">
      <div class="container-fluid">
        <!-- BEGIN LOGO -->
        <a class="brand" href="/index">
        <img src="/assets/logo.png" alt="WebAsianSystems" />
        </a>
        <!-- END LOGO -->
        <!-- BEGIN RESPONSIVE MENU TOGGLER -->
        <a class="btn btn-navbar collapsed" id="main_menu_trigger" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="arrow"></span>
        </a>
        <!-- END RESPONSIVE MENU TOGGLER -->
        <div class="top-nav">
          <div class="nav pull-right">
            <span class="user-and-role"><%=current_user.name%> (<%=current_user.user_role%>)
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
          </div>
          <!-- END TOP NAVIGATION MENU -->
        </div>
      </div>
    </div>
    <!-- END TOP NAVIGATION BAR -->
  </div>
  <!-- END HEADER -->
  <!-- BEGIN CONTAINER -->
  <div id="container" class="row-fluid">
    <!-- BEGIN SIDEBAR -->
    <div id="sidebar" class="nav-collapse collapse">
      <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
      <div class="sidebar-toggler hidden-phone"></div>
      <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
      <!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
      <div class="navbar-inverse">
        <form class="navbar-search visible-phone">
          <input type="text" class="search-query" placeholder="Search" />
        </form>
      </div>
      <!-- END RESPONSIVE QUICK SEARCH FORM -->
      <!-- BEGIN SIDEBAR MENU -->
      <ul>
        <li class="<%= active_class('/index') %>">
          <%= link_to '/index' do -%>
            <i class="icon-home"></i>
            <span class="title">Dashboard</span>
          <% end -%>
        </li>
        <% if current_user.operation? %>
          <li class="<%= active_class(customers_path) %>">
            <%= link_to customers_path do -%>
              <i class="icon-spinner"></i>
              <span class="title">Customer Details</span>
            <% end -%>
          </li>
        <% end %>
        <% if current_user.admin? || current_user.nomination? %>
          <li class="<%= active_class('upload_epxorters') %>">
            <%= link_to '/upload_epxorters' do -%>
              <i class="icon-user"></i>
              <span class="title">Upload Customer</span>
            <% end -%>
          </li>
          <li class="<%= active_class(customers_path) %>">
            <%= link_to customers_path do -%>
              <i class="icon-spinner"></i>
              <span class="title">Customer Details</span>
            <% end -%>
          </li>
        <% end %>
        <%# All users get to see the Bookings link %>
        <li class="<%= active_class('/booking_orders') %>">
          <%= link_to '/booking_orders' do -%>
            <i class="icon-file"></i>
            <span class="title">Bookings</span>
          <% end -%>
        </li>
        <% if current_user.admin? || current_user.sales? %>
          <li class="<%= active_class(sales_call_entries_path) %>">
            <%= link_to sales_call_entries_path do -%>
              <i class="icon-th-list"></i>
              <span class="title">Sales Call Entries</span>
            <% end -%>
          </li>
          <li class="<%= active_class(sales_call_enquiries_path) %>">
            <%= link_to sales_call_enquiries_path do -%>
              <i class="icon-leaf"></i>
              <span class="title">Enquiry</span>
            <% end -%>
          </li>
        <% end %>
        <% if current_user.sales? %>
          <li class="<%= active_class(new_customer_path) %>">
            <%= link_to new_customer_path do -%>
              <i class="icon-user"></i>
              <span class="title">New Customer</span>
            <% end -%>
          </li>
        <% end %>
<!--        <li class="<%= active_class('exporter_export_details') %>">
          <%= link_to '/exporter_export_details' do -%>
            <i class="icon-th-list"></i>
            <span class="title">Exporter Export Details</span>
          <% end -%>
        </li>          -->
        <% if current_user.admin? %>
          <li class="<%= active_class(emailers_path) %>">
            <%= link_to emailers_path do -%>
              <i class="icon-comment"></i>
              <span class="title">Emailer</span>
            <% end -%>
          </li>
        <% end %>

        <li class="<%= active_class(bo_reports_path) %>">
          <%= link_to bo_reports_path do -%>
            <i class="icon-bar-chart"></i>
            <span class="title">Reports</span>
          <% end -%>
        </li>
        <% if current_user.admin? %>
          <li class="<%= active_class('/bo_reports/manage') %>">
            <%= link_to "/bo_reports/manage" do -%>
              <i class="icon-bar-chart"></i>
              <span class="title">Manage Reports</span>
            <% end -%>
          </li>
        <% end %>
      </ul>
      <!-- END SIDEBAR MENU -->
    </div>
    <!-- END SIDEBAR -->
    <!-- BEGIN PAGE -->
    <div id="body" >
      <div class="container-fluid">
        <div class="row-fluid">
          <div class="span12">
            <div id="page" class="dashboard">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- END PAGE -->
  </div>
  <!-- END CONTAINER -->
  <!-- BEGIN FOOTER -->
  <div id="footer">
    2013 &copy; Euro Exim.
    <div class="span pull-right">
      <span class="go-top"><i class="icon-arrow-up"></i></span>
    </div>
  </div>
  <link rel="stylesheet" href="/chosen.css">
  <script src="/chosen.jquery.js" type="text/javascript"></script>
  <script type="text/javascript">
    jQuery(document).ready(function($) {
      $( ".datepicker" ).each(function(){
        $(this).datepicker({
          dateFormat: 'yy-mm-dd'
        });
      });
      var url = $('#tableContainer').data('source');
      var oTable = $('#tableContainer').dataTable({
        sPaginationType: "full_numbers",
        bJQueryUI: true,
        "sScrollX": "100%"
      });
    });

  </script>
</body>
</html>

app/views/layouts/devise.html.erb
	<!DOCTYPE html>
<html>
<head>
  <title>Euro Square</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	 <div id="logo" class="center" > 
		 <a href="/index" target="_blank"  style='align:middle'>
		  <img src="/assets/logo.png" alt="Web Asian Systems logo" style='margin-left:25px;' class="center">
		  <img src="/soft_logo.jpg" alt="Web Asian Systems logo" style='width:73px;' class="pull-right">
		  </a> 
	 	</div>

	 <div id="login">
	 	    <div class="control-group error">
      <div class="controls">
        <div class="help-inline">
	  	    <% flash.each do |key, value| %>
				    <div style="margin-top: 20px; padding: 0pt 0.7em;"> 
				      <p>
				        <span style="float: left; margin-right: 0.3em;"></span>					
				        <strong><%= content_tag(:div, value) %></strong>
				        <% if defined?(flush_flash) and flush_flash == true %>
				          <% flash.clear %>
				        <% end %>
				      </p>
				    </div>
		  		<% end %>
		  			<% if resource.errors.any? %>
			  		 <% resource.errors.full_messages.each do |error| %>
			  		 	<strong><%= content_tag(:div, error) %></strong>
			  		 <% end %>
			  		<% end %>
        </div>
      </div>
    </div>

		<%= yield %>
	</div>
  <div id="login-copyright">
    2013 © EuroExim. All Rights Reserved <br><br>

  <!-- END COPYRIGHT -->
  <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
  <!-- END CORE PLUGINS -->
  <!-- BEGIN PAGE LEVEL SCRIPTS -->
  <!-- END PAGE LEVEL SCRIPTS --> 
  <script>
    jQuery(document).ready(function() {     
      // initiate layout and plugins
      App.init();
      Login.init();
    });
  </script>
  <!-- END JAVASCRIPTS -->


</div>	
</body>
</html>

app/views/layouts/jbc.html.erb
	<!DOCTYPE html>
<html>
<head>
  <title>JBC</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
<!--   <%= stylesheet_link_tag    "bootstrap.min.css", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap-responsive.min.css", :media => "all" %>
  <%= stylesheet_link_tag    "style.css", :media => "all" %>
  <%= stylesheet_link_tag    "style-responsive.css", :media => "all" %>
  <%= stylesheet_link_tag    "default.css", :media => "all" %>
  <%= stylesheet_link_tag    "uniform.default.css", :media => "all" %> -->

  <!-- %link{:href => "assets/plugins/bootstrap/css/bootstrap.min.css", :rel => "stylesheet"}/
%link{:href => "assets/plugins/bootstrap/css/bootstrap-responsive.min.css", :rel => "stylesheet"}/
%link{:href => "assets/plugins/font-awesome/css/font-awesome.css", :rel => "stylesheet"}/
%link{:href => "assets/css/style.css", :rel => "stylesheet"}/
%link{:href => "assets/css/style-responsive.css", :rel => "stylesheet"}/
%link#style_color{:href => "assets/css/themes/default.css", :rel => "stylesheet"}/
%link{:href => "assets/plugins/uniform/css/uniform.default.css", :rel => "stylesheet", :type => "text/css"}/ -->
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery-1.8.3.min" %>
  <%= csrf_meta_tags %>
</head>
<body>
<body class="fixed-top">
	<!-- BEGIN HEADER -->
	<div id="header" class="navbar navbar-inverse navbar-fixed-top">
		<!-- BEGIN TOP NAVIGATION BAR -->
		<div class="navbar-inner">
			<div class="container-fluid">
				<!-- BEGIN LOGO -->
				<a class="brand" href="/index">
				<img src="assets/logo.png" alt="JBC" />
				</a>
				<!-- END LOGO -->
				<!-- BEGIN RESPONSIVE MENU TOGGLER -->
				<a class="btn btn-navbar collapsed" id="main_menu_trigger" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="arrow"></span>
				</a>          
				<!-- END RESPONSIVE MENU TOGGLER -->				
				<div class="top-nav">
					<ul class="nav pull-right" id="top_menu">
						<li class="divider-vertical hidden-phone hidden-tablet"></li>
						<!-- BEGIN USER LOGIN DROPDOWN -->
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<i class="icon-user"></i>
							<b class="caret"></b>
							</a>
							<ul class="dropdown-menu">

								<li class="divider"></li>
								<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
							</ul>
						</li>
						<!-- END USER LOGIN DROPDOWN -->
					</ul>
					<!-- END TOP NAVIGATION MENU -->	
				</div>
			</div>
		</div>
		<!-- END TOP NAVIGATION BAR -->
	</div>
	<!-- END HEADER -->
	<!-- BEGIN CONTAINER -->
	<div id="container" class="row-fluid">
		<!-- BEGIN SIDEBAR -->
		<div id="sidebar" class="nav-collapse collapse">
			<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
			
			<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
			<!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
			<div class="navbar-inverse">
				<form class="navbar-search visible-phone">
					<input type="text" class="search-query" placeholder="Search" />
				</form>
			</div>
			<!-- END RESPONSIVE QUICK SEARCH FORM -->
			<!-- BEGIN SIDEBAR MENU -->        	

			<!-- END SIDEBAR MENU -->
		</div>
		<!-- END SIDEBAR -->
		<!-- BEGIN PAGE -->
		<div id="body" style='margin-left:5px;'>
			<div class="container-fluid">
				<div class="row-fluid">
					<div class="span12">
						<div id="page" class="dashboard">
							<%= yield %>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- END PAGE -->
	</div>
	<!-- END CONTAINER -->
	<!-- BEGIN FOOTER -->
	<div id="footer">
		2013 &copy; Euro Exim.
		<div class="span pull-right">
			<span class="go-top"><i class="icon-arrow-up"></i></span>
		</div>
	</div>							
</body>
</html>